---
title: "cc_2026_day1"
author: "Lyndsay Miles"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
30 Day Chart Challenge 2026 Day 1: Part to Whole
Topic: Global Health Spending (tidytuesday)
```{r}
library(tidyverse)
library(ggplot2)
library(RColorBrewer)
library(extrafont)
```

```{r}
financing_schemes <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2026/2026-04-21/financing_schemes.csv')
health_spending <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2026/2026-04-21/health_spending.csv')
spending_purpose <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2026/2026-04-21/spending_purpose.csv')
```
Cleaning - select USA and percentage values
```{r}
spending_purpose_usa <- spending_purpose %>%
  filter(iso3_code == "USA", 
         unit == "% of current health expenditure", 
         year == "2023") %>%
  group_by(spending_purpose) %>%
  summarize(pct_raw = sum(value)) %>%
  mutate(
    spending_purpose = recode(spending_purpose,
      "Governance, and health system and financing administration"    = "Governance & admin",
      "Medical goods (non-specified by function)"                     = "Medical goods",
      "Other health care services not elsewhere classified (n.e.c.)" = "Other health care",
      "Long-term care (health)"                                       = "Long-term care"
    )
  )
```
Add dyslexic-friendly fonts
```{r}
font_add_google("Atkinson Hyperlegible", "atkinson")
showtext_auto()
```
Plot
```{r}
ggplot(grid_df, aes(x = x, y = y, fill = spending_purpose)) +
  geom_tile(color = "white", linewidth = 0.8) +
  scale_fill_brewer(palette = "BrBG")+
  coord_equal() +
  labs(
    title   = "The U.S. Health System Is Structured to Treat, Not Prevent",
    subtitle = "Each square = 1% of total health spending in 2023",
    caption = "Source: WHO Global Health Expenditure Database (GHED) | #tidytuesday \nCreated by: Lyndsay Miles",
    fill    = NULL
  ) +
  theme_void() +
  theme(
    text       = element_text(family = "atkinson"),
    plot.title      = element_text(family = "atkinson", face = "bold", size = 16, hjust = 0,
                                   margin = margin(b = 10)),
    plot.subtitle      = element_text(face = "bold", size = 12, hjust = 0,
                                   margin = margin(b = 10)),
    plot.caption    = element_text(size = 8, color = "gray50", hjust = 0,
                                   margin = margin(t = 10)),
    legend.position = "right",
    legend.text     = element_text(size = 9),
    plot.margin     = margin(15, 15, 15, 15),
    panel.background = element_rect(fill = "#FAF0E6", colour = "#704214"),
    plot.background = element_rect(fill = "#FAF0E6", colour = NA)
  ) +
  guides(fill = guide_legend(ncol = 1)) 
```
Text: Day 1 of the #30DayChartChallenge, Part to Whole. Here is a waffle chart made with #Rstats (#ggplot2) that shows how health funds were spent in the U.S. in 2023. 
I used this week's #tidytuesday dataset for this chart.
