---
title: "cc_2026_day24"
author: "Lyndsay Miles"
date: "`r Sys.Date()`"
output: html_document
---
#Day24 #30DayChartChallenge: Timeseries - Theme Day (Unicef)
Let's start with UNICEF which is the next theme day: https://data.unicef.org/resources/resource-type/datasets/
Indicator: immunization (measles, 2nd dose)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(showtext)
library(ggtext)
```

```{r}
measles <- read_csv("data/fusion_GLOBAL_DATAFLOW_UNICEF_1.0_.IM_MCV2.csv")

```

```{r}
df <- measles %>% 
  rename_with(~ tolower(gsub(" ", "_", str_extract(., "^[^:]+"), fixed = TRUE)))%>%
  select(2:9) %>% 
  filter(ref_area %in% c("SYC: Seychelles", "CPV: Cabo Verde", "MUS: Mauritius" )) 

df |> 
  select(ref_area, time_period, obs_value) |>
  arrange(ref_area, time_period) |>
  print(n = 50)

africa <- measles |> 
  filter(`REF_AREA:Geographic area` == "WHO_AFRO: Africa (WHO regions)",
         `TIME_PERIOD:Time period` == "2024"
)
```

```{r}
df_clean <- df |>
  mutate(country = str_extract(ref_area, "(?<=: ).+"))

p <- ggplot(df_clean, aes(x = time_period, y = obs_value, color = country)) +
  geom_line(linewidth = 1.1) +
  geom_point(size = 2) +
  geom_hline(yintercept = 95, linetype = "dashed", color = "gray40", linewidth = 0.5) +
  geom_hline(yintercept = 90, linetype = "dotted", color = "gray60", linewidth = 0.5) +
  annotate("rect", xmin = 2001, xmax = 2024, ymin = 95, ymax = 100,
         fill = "#1cabe2", alpha = 0.08)+
  annotate("text", x = 2001, y = 96.5, label = "95% herd immunity threshold",
           size = 2.8, color = "gray40", hjust = 0) +
  annotate("text", x = 2001, y = 91.5, label = "90% WHO target",
           size = 2.8, color = "gray60", hjust = 0) +
  annotate("rect", xmin = 2024.5, xmax = 2025.5, ymin = 0, ymax = Inf,
           fill = "#1D9E75", alpha = 0.1) +

  scale_color_manual(values = c(
  "Cabo Verde" = "#E8A020",
  "Mauritius" = "#1d3557",   # UNICEF dark blue
  "Seychelles" = "#1cabe2"   # UNICEF cyan
)) +
  scale_x_continuous(breaks = seq(2001, 2024, by = 2)) +
  scale_y_continuous(limits = c(70, 100)) +
  labs(
    title = "Sub-Saharan Africa's First Measles-Free Countries (2025)",
    subtitle = "Measles elimination built on decades of high 2nd dose vaccination coverage",
    caption = "Source: UNICEF. Note: y-axis begins at 70% to show variation in high-coverage range\n#30DayChartChallenge Day 24 | Created by: Lyndsay Miles",
    y = "% coverage", color = NULL, x = NULL) +
  theme_minimal(base_size = 16, base_family = "roboto") +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank(),
    panel.grid.major.y = element_line(color = "grey90", linewidth = 0.3),
    panel.grid.major.x = element_line(color = "grey90", linewidth = 0.3,
                                      linetype = "dashed"),
    plot.title = element_text(size = 24, face = "bold", color = "#1cabe2"),
    plot.subtitle = element_text(size = 16, color = "grey50", family = "roboto",
                                 margin = margin(b = 15)),
    plot.caption = element_text(size = 12, color = "grey60"),
    plot.background = element_rect(fill = "#eef6fb", color = NA),
    panel.background = element_rect(fill = "#eef6fb", color = NA),
    axis.text.x = element_text(size = 14),
    axis.text.y = element_text(size = 14, color = "grey50")
  )

ggsave("img/cc_2026_day24.png", p, width = 12, height = 6.27, dpi = 300)
p
  
```

