---
title: "cc_2026_day30"
author: "Lyndsay Miles"
date: "`r Sys.Date()`"
output: html_document
---
#30DayChartChallenge Day 30 — GBD
Deaths - Cause of death or injury - cardiovascular disease (all, including stroke) - All ages - both genders - 2023 - Oregon

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
cvd_deaths <- read_csv("data/IHME-GBD_2023_DATA_cvdeaths_2023_OR.csv")

```

```{r}
View(cvd_deaths)
```

```{r}
df <- cvd_deaths %>% 
  filter(metric_name == "Rate", 
         cause_name == "Cardiovascular diseases",
         !age_name %in% c("50-69 years", "50-74 years", "80+ years")) %>%
  select(sex_name, age_name, metric_name, val, upper, lower) %>%
  #for diverging plot
  mutate(
    val_plot = ifelse(sex_name == "Female", -val, val),
    upper_plot = ifelse(sex_name == "Female", -lower, upper),
    lower_plot = ifelse(sex_name == "Female", -upper, lower),
    age_name   = factor(age_name, levels = c(
      "30-34 years", "35-39 years", "40-44 years", "45-49 years",
      "50-54 years", "55-59 years", "60-64 years", "65-69 years",
      "70-74 years", "75-79 years")))
```


```{r}
# Plot
p <- ggplot(df, aes(x = val_plot, y = age_name, color = sex_name)) +
  geom_vline(xintercept = 0, color = "gray50", linewidth = 0.3) +
  geom_errorbarh(aes(xmin = lower_plot, xmax = upper_plot),
               height = 0, linewidth = 3, alpha = 0.3)+
  geom_point(size = 2.5) +
  scale_x_continuous(
  labels = function(x) abs(x),
  breaks = c(-1250, -1000, -750, -500, -250, 0, 250, 500, 750, 1000, 1250),
  limits = c(-1235, 1400),
  expand = expansion(mult = 0.05)
)+
  scale_color_manual(values = c("Female" = "#E07A8A", "Male" = "#5B8DB8")) +
  labs(
    title = "Cardiovascular Disease Mortality by Age and Sex",
    subtitle = "Oregon, 2023 | Rate per 100,000 with 95% Uncertainty Intervals",
    x = NULL,
    y = NULL,
    color = NULL,
    caption = "Source: IHME Global Burden of Disease 2023\n#30DayChartChallenge | Created by: Lyndsay Miles"
  ) +
  annotate("text", x = -200, y = 10.25, label = "Female", 
           color = "#E07A8A", fontface = "bold", hjust = 1) +
  annotate("text", x = 200, y = 10.25, label = "Male", 
           color = "#5B8DB8", fontface = "bold", hjust = 0) +
  theme_minimal(base_size = 16)+
    theme(
      legend.position = "none",
      axis.text   = element_text(colour = "white"),
      axis.title.y = element_text(colour = "white", angle = 90, size = 9),
      plot.background   = element_rect(fill = "#1C2B3A", colour = NA),
      panel.background  = element_rect(fill = "#1C2B3A", colour = NA),
      plot.title = element_text(color = "white",
        size = 24, hjust = 0.5,margin = margin(b = 8)),
      plot.subtitle     = element_text(color = "white", size = 16,
                                     hjust = 0.5, margin = margin(b = 12)),
    plot.caption      = element_text(colour = "white", size = 10,
                                     hjust = 1, margin = margin(t = 10)),
    plot.margin       = margin(20, 25, 15, 25),
    panel.grid.major = element_line(colour = "#2E4057", linewidth = 0.3),
    panel.grid.minor = element_blank(),
    coord_cartesian(xlim = c(-1000, 1400), clip = "off")
  )

ggsave("img/cc_2026_day30.png", p, width = 12, height = 6.27, dpi = 300)
p  
```
